### ISSUE TITLE
TypeError: L.KML is not a constructor

### ISSUE THREAD

**Issue by italocbrito** [aviklai/react-leaflet-kml#10]
Hi,

I'm trying to run this lib but whenever I load <ReactLeafletKml /> I'm facing a 'TypeError: L.KML is not a constructor' error. I'm loading leaflet@1.7.1 and react-leaflet@3.0.2. I also downloaded leaflet-kml and imported L.KML.js.

Would appreciate any input on the issue at hand.

Here's my code:

```
export default function DashboardMap() {
  const [kml, setKml] = React.useState(null);

  React.useEffect(() => {
    fetch(myKML)
      .then((res) => res.text())
      .then((kmlText) => {
        const parser = new DOMParser();
        const kml = parser.parseFromString(kmlText, "text/xml");
        setKml(kml);
      });
  }, []);

  return (
    <MapContainer
      center={[37.422, -122.084]}
      zoom={15}
      scrollWheelZoom={true}
      id="dashMapId"
    >
      <TileLayer
        attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />

      {kml && <ReactLeafletKml kml={kml} />}

    </MapContainer>
  );
}
```

**Comment by aviklai** [comment]
@italocbrito Hi,

Can you please add a codesandbox example?

**Comment by italocbrito** [comment]
@aviklai thanks for the quick reply. Here's the codesandbox example showing the error. Once again, appreciate the help.

https://codesandbox.io/s/upbeat-butterfly-nri46

**Comment by aviklai** [comment]
@italocbrito Hi, I release a fix for this now.
Can you please check the latest version (2.0.2).
Here is a working example - I just forked your example and update the version:
https://codesandbox.io/s/distracted-franklin-5j8xy

**Comment by italocbrito** [comment]
@aviklai Thank you very much.  I'll give it a try now.

**Comment by italocbrito** [comment]
It's working perfectly now, thank you.
