### ISSUE TITLE
KML file download all image and not acting as per minLodPixels values

### ISSUE THREAD

**Issue by lysaan** [aviklai/react-leaflet-kml#11]
An Image should be downloaded when zooming reaches `<minLodPixels>200</minLodPixels>` value but this is not happening.
All images are downloaded when map rendering starts. If there are thousands of images then this is not going to work. 
In Ideal condition images should be loaded w.r.t map center and zooming level. As it happens in Google Maps.
` <Folder>
      <Region>
        <LatLonAltBox>
          <west>174.96510016880586</west>
          <east>174.99828859706068</east>
          <south>-37.147368506798173</south>
          <north>-37.12079474453428</north>
        </LatLonAltBox>
        <Lod>
          <minLodPixels>200</minLodPixels>
          <maxLodPixels>-1</maxLodPixels>
        </Lod>
      </Region>
      <GroundOverlay>
        <LatLonBox>
          <west>174.96510016880586</west>
          <east>174.99828859706068</east>
          <south>-37.147368506798173</south>
          <north>-37.12079474453428</north>
        </LatLonBox>
        <drawOrder>1</drawOrder>
        <Icon>
          <href>a.png</href>
        </Icon>
      </GroundOverlay>
      <name>a.png</name></Folder>`

**Comment by aviklai** [comment]
@lysaan Hi,

This library is a react wrapper of leaflet-kml by windycom (originally written by Pavel Shramov):
https://github.com/windycom/leaflet-kml

I checked and it looks like there is no support for minLodPixels and maxLodPixels yet.
Can you please post the issue there?

**Comment by lysaan** [comment]
Ok thanks, I have posted the issue there too. I hope this feature will be added to Library.

**Comment by lysaan** [comment]
Well my initial suggestion was not that efficient. I have solved this issue and my suggestion is following, 
_Extract kmz on server and save images, update kml with images urls. Now when client wants to open a kmz file sent updated kml file in response. By this approach you can render large files in GB very smoothly on client end._
