### ISSUE TITLE
support for kmz files

### ISSUE THREAD

**Issue by FelipeAfonso** [aviklai/react-leaflet-kml#6]
Hi, I'd like to know how can I integrate it (is it's possible) with a kmz. Or if there is plans to add support for it in the future.

**Comment by aviklai** [comment]
Hi,

If you have a kmz that contains only a kml file inside, you can use js libraries like:
https://stuk.github.io/jszip/
https://github.com/nodeca/pako
and extract the kml file from the kmz file and use react-leaflet-kml to show the kml.
However, if the kmz file contains assets as well (like markers), it is not currently supported in the leaflet-kml library.

**Comment by FelipeAfonso** [comment]
Ok, thank you for the answer!
